version: '3.9' # optional since v1.27.0
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    tty: true

  node:
    image: smartcontract/chainlink:0.9.4
    command: local n -p /run/secrets/chainlink_password -a /run/secrets/chainlink_api
    ports:
      - '6688:6688'
    depends_on:
      - db
    env_file:
      - ./chainlink.env
    volumes:
      - 'node-data:/chainlink'
    secrets:
      - chainlink_password
      - chainlink_api
    tty: true
    stdin_open: true

  adapter:
    build:
      context: .
      args:
        - name=apy-finance
        - adapter=composite/apy-finance
    ports:
      - '8080:8080'
    environment:
      - RPC_URL=http://docker.for.mac.localhost:8545
      - REGISTRY_ADDRESS=0x7ec81b7035e91f8435bdeb2787dcbd51116ad303
      - DATA_PROVIDER=coingecko
    tty: true
    stdin_open: true

secrets:
  chainlink_password:
    file: ./.password
  chainlink_api:
    file: ./.api

volumes:
  db-data:
  node-data:
