version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres
    expose:
        - "5432"
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
    network_mode: host
    tty: true

  chainlink:
    image: smartcontract/chainlink:0.9.4
    network_mode: host
    expose:
        - "6688"
    depends_on:
        - postgres
    env_file:
        - ./chainlink.env
    volumes:
        - ~/.chainlink:/chainlink
    tty: true

networks:
    chainlink:
